
repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt (ruff --fix + black)
        entry: poetry run fmt
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: lint
        name: lint (ruff + black --check)
        entry: poetry run lint
        language: system
        pass_filenames: false
        stages: [pre-push]
